version: '3.8'
services:
  app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    # для отладки, чтобы не скачивать каждый раз данные, я пробрасываю папку /data/
    volumes:
    - type: bind
      source: ./data
      target: /data
    # в этом варианте запускается только тест
    # ключ -s у pytest не даёт ему перехватывать вывод, мне кажется полезно видеть лог, особенно если возникнут ошибки
    command: bash -c "python3 -m pytest tests -s --disable-pytest-warnings"
    ports:
      - 8000:8000
    environment:
      PYTHONUNBUFFERED: 1
    image: jenyanorilsk/mle_lab2:latest
