pipeline {

    agent any

    environment {
        DOCKERHUB_CREDS = credentials('mle-lab-docker')
        LC_ALL = "ru_RU.UTF-8"
        LANG    = "ru_RU.UTF-8"
        LANGUAGE = "ru_RU.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}

    stages {

        stage('Clone github repository') {
            steps {
                cleanWs()
                bat encoding: 'UTF-8', script: '''
                    chcp 65001
                    git clone -b main https://github.com/jenyanorilsk/mle_2_homework.git'''
            }
        }

        stage('Checkout repo dir') {
            steps {
                bat encoding: 'UTF-8', script: '''
                                                chcp 65001
                                                cd mle_2_homework && dir'''
            }
        }

        stage('Login'){
            steps {

                bat encoding: 'UTF-8', script: '''
                    chcp 65001
                    docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%
                    '''
            }
        }
       
        stage('Create and run docker container') {
            steps {
                script {
                    try {
                        bat encoding: 'UTF-8', script: '''
                            chcp 65001
                            cd mle_2_homework && docker-compose -f docker-compose-CD.yml build'''
                    }
                    finally {
                        //bat encoding: 'UTF-8', script: '''
                        //    chcp 65001
                        //    cd mle_2_homework
                        //    docker-compose -f docker-compose-CD.yml up -d
                        //    '''
                    }
                }
            }
        }

        stage('Checkout container logs') {
            steps {
                dir("mle_2_homework") {
                        bat encoding: 'UTF-8', script: '''
                            chcp 65001
                            docker-compose -f docker-compose-CD.yml up -d
                            for /f %%i in ('docker ps -qf "name=^mle_2_homework_app_1"') do set containerId=%%i
                            echo %containerId%
                            IF "%containerId%" == "" (
                                echo "No container running"
                            )
                            ELSE (
                                docker logs --tail 1000 -f %containerId%
                                )
                        '''
                    }
            }
        }

        stage('Checkout coverage report'){
            steps{
                dir("mle_2_homework"){
                    bat encoding: 'UTF-8', script: '''
                        chcp 65001
                        docker-compose logs -t --tail 10
                    '''
                }
            }
        }

        stage('Push'){
            steps{
                bat encoding: 'UTF-8', script: '''
                    chcp 65001
                    docker push jenyanorilsk/mle_lab2:latest'''
            }
        }

    }

    post {
        always {
            bat encoding: 'UTF-8', script: '''
                    chcp 65001
                    docker logout
                    '''
        }
    }

}